import React from "react";
import { Button, Image, Modal } from "semantic-ui-react";

//Modal for Help option
export default function BrewModal() {
  const [open, setOpen] = React.useState(false);

  return (
    <Modal
      open={open}
      onClose={() => setOpen(false)}
      onOpen={() => setOpen(true)}
      trigger={
        <Button
          style={{
            FontFace: "font-family: Press Start 2P, cursive;",
            backgroundColor: "white",
            borderRadius: "25px",
          }}
          className="ui black button large basic"
          id="pkBtn"
        >
          Help
        </Button>
      }
    >
      <Modal.Header>
        <div style={{ textAlign: "center" }}>Helpful Info</div>
      </Modal.Header>
      <Modal.Content image>
        <Image wrapped />
        <Modal.Description>
          <div id="pokeModalDesc">
            <h3 style={{ paddingTop: "10px" }}>Pokdex Javascript Info</h3>
            <p>
              Welcome to this small web app! The first option you have available
              is searching by pokemon name. You can also enter a pokemon's ID if
              you know it. Once you filled out the input field you can either
              press enter or select the search icon.
            </p>
            <b>Beware:</b>
            <p>
              If you enter a pokemon's name incorrectly, you won't get any
              results back.
            </p>
            <hr />
            <h3>Search Options</h3>
            <p>
              You also have the option to retrieve a list of pokemon. To do this
              you'll select the Collection option in the advanced Search. Once
              selected, enter the number of pokemon you want to receive and the
              list should generate the amount of pokemon you entered. It tries
              it's best to list them out in order but doesn't always work.
            </p>
            <hr />
            <h3>Resetting page</h3>
            <p>You can easily clear the list of pokemon by clicking Reset. </p>
            <hr />
            <h3>Random Fetching</h3>
            <p>
              If you click the Pokeball you will retrieve a random pokemon.
              Incase you're wondering how this works, here's an explanation
              below:
            </p>
            <br />
            <p>
              A random number between 1 - 898 is generated by a built in Math
              function from Javascript. I chose to round the number down to the
              floor.
            </p>
            <hr />
            <h3>Sourcing Pokemon Information</h3>
            <p>
              Any information about the pokemon and access to it's data is
              provided by the{" "}
              <a
                target="_blank"
                href="https://pokeapi.co/"
                rel="noreferrer"
                style={{ color: "red", fontSize: "20px" }}
              >
                PokeDex API (Application Programming Interface)
              </a>{" "}
              Keep in mind that the data set is open source and is maintained by
              generous individuals.
            </p>
          </div>
          {/* <!-- end stats--> */}
        </Modal.Description>
      </Modal.Content>
      <Modal.Actions>
        <Button negative onClick={() => setOpen(false)}>
          Close
        </Button>
      </Modal.Actions>
    </Modal>
  );
}
